export CUDA_VISIBLE_DEVICES=4


#load pretrained DERT encoder and train Dateformer
python -u run.py --mode 1 --pretrain mean --data ExchangeRate --root_path ./data/exchange_rate --lookback_window 7 --lookback_len 7 --horizon_len 1 --train_scale 7 1 --val_scale 7 1 --d_sequences 8 --d_features 79 --d_model 512 --e_layers 2 4 --d_layers 4 --n_heads 8 --d_ff 2048 --n_predays 7 --n_postdays 14 --granularity 1 --dropout 0.1 --prenorm --max_len 800 --features abs_days year day year_day week lunar_year lunar_month lunar_day lunar_year_day dayofyear dayofmonth monthofyear dayofweek dayoflunaryear dayoflunarmonth monthoflunaryear --localized date holidays workdays residual_holiday residual_workday jieqiofyear jieqi_day dayofjieqi --test_scale 47 96 --test_scale 61 192 --test_scale 76 336 --test_scale 114 720 --des 'pretrained'
  # skip warm up
python -u run.py --mode 1 --pretrain mean --data ExchangeRate --root_path ./data/exchange_rate --lookback_window 7 --lookback_len 7 --horizon_len 1 --train_scale 7 1 --val_scale 7 1 --d_sequences 8 --d_features 79 --d_model 512 --e_layers 2 4 --d_layers 4 --n_heads 8 --d_ff 2048 --n_predays 7 --n_postdays 14 --granularity 1 --dropout 0.1 --skip_warmup --prenorm --max_len 800 --features abs_days year day year_day week lunar_year lunar_month lunar_day lunar_year_day dayofyear dayofmonth monthofyear dayofweek dayoflunaryear dayoflunarmonth monthoflunaryear --localized date holidays workdays residual_holiday residual_workday jieqiofyear jieqi_day dayofjieqi --test_scale 47 96 --test_scale 61 192 --test_scale 76 336 --test_scale 114 720 --des 'pretrained without warmup'


#train Dateformer from scratch
python -u run.py --mode 1 --data ExchangeRate --root_path ./data/exchange_rate --lookback_window 7 --lookback_len 7 --horizon_len 1 --train_scale 7 1 --val_scale 7 1 --d_sequences 8 --d_features 79 --d_model 512 --e_layers 2 4 --d_layers 4 --n_heads 8 --d_ff 2048 --n_predays 7 --n_postdays 14 --granularity 1 --dropout 0.1 --from_scratch --prenorm --max_len 800 --features abs_days year day year_day week lunar_year lunar_month lunar_day lunar_year_day dayofyear dayofmonth monthofyear dayofweek dayoflunaryear dayoflunarmonth monthoflunaryear --localized date holidays workdays residual_holiday residual_workday jieqiofyear jieqi_day dayofjieqi --test_scale 47 96 --test_scale 61 192 --test_scale 76 336 --test_scale 114 720 --des 'from scratch'
  # skip warm up
python -u run.py --mode 1 --data ExchangeRate --root_path ./data/exchange_rate --lookback_window 7 --lookback_len 7 --horizon_len 1 --train_scale 7 1 --val_scale 7 1 --d_sequences 8 --d_features 79 --d_model 512 --e_layers 2 4 --d_layers 4 --n_heads 8 --d_ff 2048 --n_predays 7 --n_postdays 14 --granularity 1 --dropout 0.1 --from_scratch --skip_warmup --prenorm --max_len 800 --features abs_days year day year_day week lunar_year lunar_month lunar_day lunar_year_day dayofyear dayofmonth monthofyear dayofweek dayoflunaryear dayoflunarmonth monthoflunaryear --localized date holidays workdays residual_holiday residual_workday jieqiofyear jieqi_day dayofjieqi --test_scale 47 96 --test_scale 61 192 --test_scale 76 336 --test_scale 114 720 --des 'from scratch without warmup'


#pretrain DERT encoder
python -u run.py --mode 0 --pretrain mean --data ExchangeRate --root_path ./data/exchange_rate --batch_size 8192 --d_sequences 8 --d_features 79 --d_model 512 --e_layers 2 4 --d_layers 4 --n_heads 8 --d_ff 2048 --n_predays 7 --n_postdays 14 --granularity 1 --dropout 0.1 --prenorm --features abs_days year day year_day week lunar_year lunar_month lunar_day lunar_year_day dayofyear dayofmonth monthofyear dayofweek dayoflunaryear dayoflunarmonth monthoflunaryear --localized date holidays workdays residual_holiday residual_workday jieqiofyear jieqi_day dayofjieqi --des pretrain
